# Lista de cursos y URLs para los horarios
cursos:
  - curso: "Primero"
    url: "https://www.usc.gal/es/course/widget/76/course-detail-controller-week-filter/5060/19627-1/25/42?_wrapper_format=drupal_ajax"

  - curso: "Segundo"
    url: "https://www.usc.gal/es/course/widget/76/course-detail-controller-week-filter/5060/11930-2/25/42?_wrapper_format=drupal_ajax"

  - curso: "Tercero"
    url: "https://www.usc.gal/es/course/widget/76/course-detail-controller-week-filter/5060/11930-3/25/42?_wrapper_format=drupal_ajax"

  - curso: "Cuarto"
    url: "https://www.usc.gal/es/course/widget/76/course-detail-controller-week-filter/5060/11930-4/25/42?_wrapper_format=drupal_ajax"

  - curso: "Primero Mates-Física"
    url: "https://www.usc.gal/es/course/widget/76/course-detail-controller-week-filter/5050/15968-1/25/42?_wrapper_format=drupal_ajax"
  - curso: "Segundo Mates-Física"
    url: "https://www.usc.gal/es/course/widget/76/course-detail-controller-week-filter/5050/15968-2/25/42?_wrapper_format=drupal_ajax"
  - curso: "Tercero Mates-Física"
    url: "https://www.usc.gal/es/course/widget/76/course-detail-controller-week-filter/5050/15968-3/25/42?_wrapper_format=drupal_ajax"
  - curso: "Cuarto Mates-Física"
    url: "https://www.usc.gal/es/course/widget/76/course-detail-controller-week-filter/5050/15968-4/25/42?_wrapper_format=drupal_ajax"
  - curso: "Quinto Mates-Física"
    url: "https://www.usc.gal/es/course/widget/76/course-detail-controller-week-filter/5050/15968-5/25/42?_wrapper_format=drupal_ajax"

chrome_data_dir: python\horarios\chrome\selenium
chromedriver_path: python\horarios\chrome\chromedriver.exe
timetable_path: python\horarios\output\horario.csv
forms_data_path: python\horarios\output\forms_data.json
